version: '3.8'

services:

  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_SCHEMA:-render}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASS:-pass}