databases:
  - name: pg_db
    region: frankfurt
    plan: starter

services:
  - type: web
    name: spring-dockerized-service
    runtime: docker
    region: frankfurt
    plan: free
    healthCheckPath: /
