#databases:
#  - name: pg_db
#    region: frankfurt
#    plan: starter

services:
  - type: web
    name: spring-dockerized-service
    runtime: docker
    region: frankfurt
    plan: free
    healthCheckPath: /

  - type: web
    name: spring-consumer
    runtime: docker
    url: aurelo/spring_consumer:latest
    region: frankfurt
    plan: free
    healthCheckPath: /

  # A Redis instance
  - type: redis
    name: lightning
    region: frankfurt
    ipAllowList: # required
      - source: 0.0.0.0/0
        description: everywhere
    plan: free # optional (defaults to starter instance type)
    maxmemoryPolicy: noeviction # optional (defaults to allkeys-lru)
